[manager]
prepend_keymap = [
  { on = "L", run = "open" },
  { on = "<Esc>", run = "quit" },
  { on = "M", run = "plugin mount" },
  { on = [
    "<Right>",
  ], run = "plugin fuse-archive 'mount'", desc = "Enter or Mount selected archive" },
  { on = [
    "<Left>",
  ], run = "plugin fuse-archive 'unmount'", desc = "Leave or Unmount selected archive" },
]
